enum TreeStateActionType {
    SWITCH_TREE_SELECTOR = "SWITCH_TREE_SELECTOR",

    CHANGE_NODE_EXPAND = "CHANGE_NODE_EXPAND",
    CHANGE_NODE_FILTER_QUERY = "CHANGE_NODE_FILTER_QUERY"
}
export default TreeStateActionType;