enum CommonActionType {
    CONNECT_TO_SERVER = "CONNECT_TO_SERVER",
    CONNECTION_ESTABLISHED = "CONNECTION_ESTABLISHED",

    GET_FRAMES = "GET_FRAMES",
    PUT_FRAME = "PUT_FRAME",

    SELECT_TREE = "SELECT_TREE",
    NOTIFY_TREE_STRUCTURE = "NOTIFY_TREE_STRUCTURE",

    SELECT_NODE = "SELECT_NODE",
    NOTIFY_ATTRIBUTE_CHANGE = "NOTIFY_ATTRIBUTE_CHANGE",

    CHANGE_ADJUST_SCREEN_TYPE = "CHANGE_ADJUST_SCREEN_TYPE",
    EPIC_CHANGE_ADJUST_SCREEN_TYPE = "EPIC_CHANGE_ADJUST_SCREEN_TYPE"
}

export default CommonActionType;