enum CommonActionType {
    GET_FRAMES = "GET_FRAMES",
    PUT_FRAME = "PUT_FRAME",
    SELECT_TREE = "SELECT_TREE",
    SELECT_NODE = "SELECT_NODE",
    CONNECTION_ESTABLISHED = "CONNECTION_ESTABLISHED",
    GET_FRAMES_RESPONSE = "GET_FRAMES_RESPONSE",
}

export default CommonActionType;