enum CommonActionType {
    CONNECT_TO_SERVER="CONNECT_TO_SERVER",
    CONNECTION_ESTABLISHED = "CONNECTION_ESTABLISHED",
    GET_FRAMES = "GET_FRAMES",
    PUT_FRAME = "PUT_FRAME",
    SELECT_TREE = "SELECT_TREE",
    SELECT_NODE = "SELECT_NODE",
}

export default CommonActionType;